apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-events
resources:
- ../../base
patches:
- target:
    version: v1
    group: apps
    kind: Deployment
  patch: |-
    - op: remove
      path: /spec/template/spec/securityContext/runAsUser